name: Saucedemo_05

on:
  push:
    branches: [ main, US_002.00, KateFox ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      id: setup-python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true


    - name: Install poetry dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Firefox
      uses: riccione/setup_firefox@v1
    - name: Check Chromium version
      run: chromium-browser --version
      #----------------------------------------------
      #  -----  test  -----
      #----------------------------------------------

      #----------------------------------------------


    - name: run only login
      if: always()
      run: poetry run pytest tests/test_login.py --alluredir=allure-results
      continue-on-error: true

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ALLURE_DEPLOY  }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history








