name: Saucedemo_05

on:
  push:
    branches: [ main, Kate-Sergey-KATE]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      id: setup-python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true


    - name: Install poetry dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Run tests
      run:
        poetry run pytest -v
    - name: Black and Flake8
      uses: ricardochaves/python-lint@v1.4.0
      with:
          python-root-list: ""
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--count --benchmark --ignore=E501"
          extra-black-options: ". -S"
          extra-mypy-options: ""
          extra-isort-options: ""
